line-length = 120
target-version = "py313"

[lint]
select = ["ALL"]  # include all the rules, including new ones
ignore = [
    # Modules
    "ANN",  # flake8-annotations
    "COM",  # flake8-commas
    "C90",  # mccabe complexity
    "DJ",   # django
    "EXE",  # flake8-executable
    "T10",  # debugger
    "TID",  # flake8-tidy-imports

    # Specific rules
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D200",
    "D205", "D212", "D400", "D401", "D415",
    "E402",  # false positives for local imports
    "E501",  # line too long
    "TRY003", "TD002", "TD003", "FIX002", "B904", "TRY002"
]
