name: Generate PDF documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Doxygen-Documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen \
          texlive-latex-base \
          texlive-latex-recommended \
          texlive-latex-extra \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          latexmk
      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Build PDF
        run: |
          cd docs/latex
          pdflatex refman.tex
          mv refman.pdf ../documentation.pdf

      - name: Clean up
        run: |
          cd ../
          rm -rf latex html
          cd ../

      - name: Commit PDF to repo
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add docs/documentation.pdf
          git commit -m "Update generated PDF documentation"
          git push --force