name: Ruff Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Ruff
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files > 0 && github.event.pull_request.files.*.filename == '*.py' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff check
        run: ruff check
